import type { ValuationScenario } from "./types";

export function formatDate(date: Date): string {
  return new Intl.DateTimeFormat("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  }).format(date);
}

export function generateReportContent(data: ValuationScenario): string {
  const report = `
    BUSINESS VALUATION REPORT
    Generated on ${formatDate(new Date())}
    
    EXECUTIVE SUMMARY
    ================
    Business Name: ${data.name}
    Industry: ${data.industryData.industryType}
    Valuation Date: ${formatDate(new Date(data.date))}
    
    VALUATION RANGE
    ==============
    Low Range: ${formatCurrency(data.results.valuationRange.low)}
    Mid-Point Value: ${formatCurrency(data.results.valuationRange.mid)}
    High Range: ${formatCurrency(data.results.valuationRange.high)}
    
    KEY METRICS
    ==========
    Revenue: ${formatCurrency(data.financialData.revenue)}
    EBITDA (Adjusted): ${formatCurrency(data.results.adjustedEbitda)}
    Applied Multiple: ${data.results.adjustedMultiple}x
    Value Driver Score: ${data.valueDrivers.financialScore.toFixed(1)}/5
    
    FINANCIAL ANALYSIS
    ================
    Revenue: ${formatCurrency(data.financialData.revenue)}
    EBITDA: ${formatCurrency(data.financialData.ebitda)}
    Adjustments: ${formatCurrency(data.financialData.adjustments)}
    Working Capital: ${formatCurrency(data.financialData.workingCapital)}
    Capital Expenditures: ${formatCurrency(data.financialData.capex)}
    Total Debt: ${formatCurrency(data.financialData.debt)}
    
    VALUATION METHODS
    ===============
    1. Market Multiple Analysis
    -------------------------
    Industry: ${data.industryData.industryType}
    Applied Multiple: ${data.results.adjustedMultiple}x
    Resulting Value: ${formatCurrency(data.results.businessValue)}
    
    2. Discounted Cash Flow Analysis
    -----------------------------
    Growth Rate: ${data.industryData.projectedGrowthRate}%
    Discount Rate: ${data.industryData.discountRate}%
    DCF Value: ${formatCurrency(data.results.dcfValue)}
    
    3. Asset-Based Valuation
    ----------------------
    Tangible Assets: ${formatCurrency(data.financialData.tangibleAssets)}
    Intangible Assets: ${formatCurrency(data.financialData.intangibleAssets)}
    Total Liabilities: ${formatCurrency(data.financialData.totalLiabilities)}
    Net Asset Value: ${formatCurrency(data.results.assetValue)}
    
    VALUE DRIVERS ANALYSIS
    ===================
    Financial Performance: ${data.valueDrivers.financialScore}/5
    Customer & Market Position: ${data.valueDrivers.customerScore}/5
    Operational Excellence: ${data.valueDrivers.operationalScore}/5
    Management Depth: ${data.valueDrivers.managementScore}/5
    Strategic Position: ${data.valueDrivers.strategicScore}/5
    
    ENHANCEMENT OPPORTUNITIES
    ======================
    1. Financial Performance: ${
      data.valueDrivers.financialScore < 4
        ? "Opportunity for improvement in financial metrics"
        : "Strong financial performance"
    }
    2. Customer Concentration: ${
      data.valueDrivers.customerConcentration < 0
        ? "Consider diversifying customer base"
        : "Good customer diversification"
    }
    3. Management Structure: ${
      data.valueDrivers.managementDepth < 0
        ? "Opportunity to strengthen management team"
        : "Strong management structure"
    }
    4. Growth Trajectory: ${
      data.valueDrivers.growthRate <= 0
        ? "Focus on growth initiatives"
        : "Positive growth trajectory"
    }
    
    DISCLAIMER
    =========
    This report is for informational purposes only and should not be considered a formal valuation.
    For a detailed valuation, please consult with a qualified business valuation professional.
    
    Generated by Schapira CPA Business Valuation Calculator
    © ${new Date().getFullYear()} Schapira CPA
  `;
  return report;
}

export function formatCurrency(value: number): string {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(value);
}

export function generateValuationToolData(data: ValuationScenario): string {
  // Convert the data to CSV format for spreadsheet compatibility
  const csvData = [
    ["Business Valuation Data Export"],
    ["Generated on", formatDate(new Date())],
    [""],
    ["Category", "Value"],
    ["Business Name", data.name],
    ["Industry", data.industryData.industryType],
    ["Revenue", data.financialData.revenue],
    ["EBITDA", data.financialData.ebitda],
    ["Adjustments", data.financialData.adjustments],
    ["Working Capital", data.financialData.workingCapital],
    ["Capital Expenditures", data.financialData.capex],
    ["Total Debt", data.financialData.debt],
    ["Tangible Assets", data.financialData.tangibleAssets],
    ["Intangible Assets", data.financialData.intangibleAssets],
    ["Total Liabilities", data.financialData.totalLiabilities],
    [""],
    ["Value Drivers"],
    ["Financial Score", data.valueDrivers.financialScore],
    ["Customer Score", data.valueDrivers.customerScore],
    ["Operational Score", data.valueDrivers.operationalScore],
    ["Management Score", data.valueDrivers.managementScore],
    ["Strategic Score", data.valueDrivers.strategicScore],
    [""],
    ["Results"],
    ["Business Value", data.results.businessValue],
    ["DCF Value", data.results.dcfValue],
    ["Asset Value", data.results.assetValue],
    ["Low Range", data.results.valuationRange.low],
    ["Mid Range", data.results.valuationRange.mid],
    ["High Range", data.results.valuationRange.high],
  ];

  return csvData.map((row) => row.join(",")).join("\n");
}
