export const routes = {
  home: "/",
  about: {
    index: "/about",
    approach: "/about/approach",
  },
  services: {
    index: "/services",
    manufacturingTax: "/services/manufacturing-tax",
    rdTaxCredits: "/services/rd-tax-credits",
    costAccounting: "/services/cost-accounting",
    growthFinancing: "/services/growth-financing",
    financialAnalysis: "/services/financial-analysis",
    maAdvisory: "/services/ma-advisory",
    financialForecasting: "/services/financial-forecasting",
    cashFlowOptimization: "/services/cash-flow-optimization",
    strategicTaxPlanning: "/services/strategic-tax-planning",
  },
  portfolio: {
    index: "/portfolio",
    precisionMetal: "/portfolio/precision-metal-products",
    advancedComposites: "/portfolio/advanced-composites",
    harvestFoods: "/portfolio/harvest-foods",
  },
  resources: {
    index: "/resources",
    manufacturingValuation: "/resources/manufacturing-valuation",
    manufacturingBenchmarks: "/resources/manufacturing-benchmarks",
    savingsCalculators: "/resources/savings-calculators",
    rdCalculators: "/resources/rd-calculators",
    financialGuides: "/resources/financial-guides",
    financialRatios: "/resources/financial-ratios",
    taxPlanning: "/resources/tax-planning",
  },
  blog: {
    index: "/blog",
    taxPlanning: "/blog/tax-planning",
  },
  contact: "/contact",
  consultation: "/consultation",
  manufacturingSolutions: {
    index: "/manufacturing-solutions",
    cashFlowManagement: "/manufacturing-solutions/cash-flow-management",
    costReduction: "/manufacturing-solutions/cost-reduction",
    taxCredits: "/manufacturing-solutions/tax-credits",
    successStories: "/manufacturing-solutions/success-stories",
  },
  profitMethod: {
    index: "/profit-method",
    quarterlyReviews: "/profit-method/quarterly-business-reviews",
    roiStrategy: "/profit-method/roi-driven-strategy",
    growthPlanning: "/profit-method/growth-planning-framework",
  },
  successStories: {
    index: "/success-stories",
    precisionMetal: "/success-stories/precision-metal-products",
    advancedComposites: "/success-stories/advanced-composites",
    harvestFoods: "/success-stories/harvest-foods",
  },
};
